## Variaveis que devem ser configuradas no projeto CircleCI  ##
# FIREBASE_TOKEN

version: 2.1

executors:
  nodejs:
    docker:
      - image: node:8.15.1-jessie
    working_directory: /home/circleci
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - attach_workspace:
          at: /home/circleci/marvel-app
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
  tests:
    executor: nodejs
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - checkout
      - attach_workspace:
          at: /home/circleci/marvel-app
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
  deploy:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-
      - attach_workspace:
          at: /home/circleci/marvel-app
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2.1
  marvel-app:
    jobs:
      - build
      - tests:
          requires:
              - build
