## Variaveis que devem ser configuradas no projeto CircleCI  ##
# FIREBASE_TOKEN

version: 2.1

executors:
  nodejs:
    docker:
      - image: node:8.15.1-jessie
    working_directory: /home/circleci
jobs:
  build:
    executor: nodejs
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install
          command: cd marvel-app && npm install
      - run:
          name: Build
          command: cd marvel-app && npm run build
  tests:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install npm
          command: cd marvel-app && npm install
      - run:
          name: Run tests
          command: npm test

  deploy:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install
          command: cd marvel-app && npm install
      - run:
          name: Build
          command: cd marvel-app && npm run build
      - run:
          name: Install Firebase Tools
          command: cd marvel-app && npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: cd marvel-app && ./firebase-deploy/node_modules/.bin/firebase deploy --token=${FIREBASE_TOKEN}

workflows:
  version: 2.1
  marvel-app:
    jobs:
      - build
      - tests:
          requires:
              - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - tests
