## Variaveis que devem ser configuradas no projeto CircleCI  ##
# FIREBASE_TOKEN

version: 2.1

executors:
  nodejs:
    docker:
      - image: node:8.15.1-jessie
    working_directory: /home/circleci
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/marvel-app
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
  tests:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/marvel-app
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Run tests
          command: npm test
workflows:
  version: 2.1
  marvel-app:
    jobs:
      - build
      - tests:
          requires:
              - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - tests
